import type { UmlModelData } from "@/types/uml";

export const INITIAL_DIAGRAM: UmlModelData = {
  nodes: [
    {
      key: "empresa-1",
      name: "Empresa",
      category: "Class",
      isAbstract: false,
      attributes: [
        { name: "nombre", type: "String", visibility: "+" },
        { name: "ruc", type: "String", visibility: "-", multiplicity: "1", isReadOnly: true },
      ],
      methods: [
        {
          name: "contratar",
          visibility: "+",
          parameters: [{ direction: "in", name: "empleado", type: "Empleado" }],
          returnType: "Boolean",
        },
        {
          name: "cantidadEmpleados",
          visibility: "+",
          parameters: [],
          returnType: "Integer",
          isStatic: true,
        },
      ],
      loc: "40 40",
    },
    {
      key: "empleado-1",
      name: "Empleado",
      category: "Class",
      isAbstract: false,
      attributes: [
        { name: "id", type: "Integer", visibility: "-", multiplicity: "1", isReadOnly: true },
        { name: "estado", type: "EstadoEmpleado", visibility: "-" },
      ],
      methods: [
        { name: "calcularSalario", visibility: "+", parameters: [], returnType: "Real" },
      ],
      loc: "380 40",
    },
    {
      key: "casa-1",
      name: "Casa",
      category: "Class",
      isAbstract: false,
      attributes: [{ name: "direccion", type: "String", visibility: "+" }],
      methods: [],
      loc: "40 380",
    },
    {
      key: "habitacion-1",
      name: "Habitacion",
      category: "Class",
      isAbstract: false,
      attributes: [{ name: "metros", type: "Real", visibility: "-", multiplicity: "1" }],
      methods: [],
      loc: "380 380",
    },
    {
      key: "cuenta-bancaria-1",
      name: "CuentaBancaria",
      category: "Class",
      isAbstract: true,
      attributes: [{ name: "saldo", type: "Real", visibility: "-" }],
      methods: [
        {
          name: "retirar",
          visibility: "+",
          parameters: [{ direction: "in", name: "monto", type: "Real" }],
          returnType: "Boolean",
          isAbstract: true,
        },
      ],
      loc: "720 40",
    },
    {
      key: "cuenta-ahorro-1",
      name: "CuentaAhorro",
      category: "Class",
      isAbstract: false,
      attributes: [{ name: "interes", type: "Real", visibility: "-" }],
      methods: [
        { name: "aplicarInteres", visibility: "+", parameters: [], returnType: "Void" },
      ],
      loc: "720 380",
    },
    {
      key: "notificable-1",
      name: "Notificable",
      category: "Interface",
      methods: [
        {
          name: "notificar",
          visibility: "+",
          parameters: [{ direction: "in", name: "mensaje", type: "String" }],
          returnType: "Void",
        },
      ],
      loc: "1060 40",
    },
    {
      key: "estado-1",
      name: "EstadoEmpleado",
      category: "Enum",
      literals: ["ACTIVO", "INACTIVO"],
      loc: "40 720",
    },
  ],
  links: [
    {
      key: "l1",
      category: "aggregation",
      from: "empresa-1",
      to: "empleado-1",
      fromRole: "+empleador",
      toRole: "+empleado",
      fromMultiplicity: "1",
      toMultiplicity: "*",
    },
    {
      key: "l2",
      category: "composition",
      from: "casa-1",
      to: "habitacion-1",
      fromMultiplicity: "1",
      toMultiplicity: "1..*",
    },
    {
      key: "l3",
      category: "generalization",
      from: "cuenta-ahorro-1",
      to: "cuenta-bancaria-1",
      fromMultiplicity: "1",
      toMultiplicity: "1",
    },
    {
      key: "l4",
      category: "realization",
      from: "empleado-1",
      to: "notificable-1",
      fromMultiplicity: "1",
      toMultiplicity: "1",
    },
    {
      key: "l5",
      category: "association",
      from: "empleado-1",
      to: "estado-1",
      fromMultiplicity: "1",
      toMultiplicity: "*",
    },
    {
      key: "l6",
      category: "dependency",
      from: "empresa-1",
      to: "notificable-1",
      fromMultiplicity: "1",
      toMultiplicity: "1",
    },
  ],
};